'use client';

import React from 'react';

interface MarkdownRendererProps {
  content: string;
}

export function MarkdownRenderer({ content }: MarkdownRendererProps) {
  if (!content) return null;

  // Split content into blocks by tables, images, or paragraphs
  const parseBlocks = (text: string) => {
    // Check for HTML image block generated by Python chatbot
    const htmlImgRegex = /<div style="text-align:center;[\s\S]*?<img src="([^"]+)"[\s\S]*?<\/div>/g;
    const parts: React.ReactNode[] = [];
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = htmlImgRegex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        const textBefore = text.slice(lastIndex, match.index);
        parts.push(renderTextAndTables(textBefore, `block-${lastIndex}`));
      }
      const imgSrc = match[1];
      parts.push(
        <div key={`img-${match.index}`} className="my-3 text-center">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imgSrc}
            alt="Analytical Chart"
            className="mx-auto max-w-full rounded-xl border border-[#E6E8EC] shadow-md"
          />
          <a
            href={imgSrc}
            download="Media_Octus_Chart.png"
            className="mt-2.5 inline-flex items-center gap-1.5 rounded-lg bg-[#6E1D1D] px-3.5 py-1.5 text-xs font-semibold text-white shadow-sm transition hover:bg-[#882424]"
          >
            <span>⬇ Download Chart</span>
          </a>
        </div>
      );
      lastIndex = match.index + match[0].length;
    }

    if (lastIndex < text.length) {
      parts.push(renderTextAndTables(text.slice(lastIndex), `block-${lastIndex}`));
    }

    return parts;
  };

  const renderTextAndTables = (text: string, keyPrefix: string) => {
    const lines = text.split('\n');
    const nodes: React.ReactNode[] = [];
    let tableLines: string[] = [];
    let isInsideTable = false;

    const flushTable = (index: number) => {
      if (tableLines.length > 0) {
        nodes.push(renderTable(tableLines, `${keyPrefix}-table-${index}`));
        tableLines = [];
      }
      isInsideTable = false;
    };

    lines.forEach((line, index) => {
      const trimmed = line.trim();
      const isTableRow = trimmed.startsWith('|') && trimmed.endsWith('|');

      if (isTableRow) {
        isInsideTable = true;
        tableLines.push(trimmed);
      } else {
        if (isInsideTable) {
          flushTable(index);
        }
        if (trimmed.length > 0) {
          nodes.push(renderLine(trimmed, `${keyPrefix}-line-${index}`));
        } else {
          nodes.push(<div key={`${keyPrefix}-space-${index}`} className="h-2" />);
        }
      }
    });

    if (isInsideTable) {
      flushTable(lines.length);
    }

    return <div key={keyPrefix}>{nodes}</div>;
  };

  const renderTable = (rows: string[], key: string) => {
    if (rows.length < 2) return null;

    // Filter out separator row (e.g. |:---|:---| or |---|---|)
    const headerRow = rows[0];
    const dataRows = rows.slice(1).filter((r) => !r.includes('---'));

    const parseCells = (rowStr: string) =>
      rowStr
        .split('|')
        .slice(1, -1)
        .map((c) => c.trim());

    const headers = parseCells(headerRow);

    return (
      <div key={key} className="my-2.5 max-w-full overflow-x-auto rounded-lg border border-[#E6E8EC] shadow-xs">
        <table className="w-full min-w-full text-left text-xs">
          <thead className="bg-[#F8E6E6] text-[#6E1D1D]">
            <tr>
              {headers.map((h, i) => (
                <th key={i} className="whitespace-nowrap px-3 py-2 font-semibold tracking-wider">
                  {formatInline(h)}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E6E8EC] bg-white">
            {dataRows.map((row, rIdx) => {
              const cells = parseCells(row);
              return (
                <tr key={rIdx} className={rIdx % 2 === 1 ? 'bg-slate-50/50' : 'bg-white'}>
                  {cells.map((cell, cIdx) => (
                    <td key={cIdx} className="px-3 py-2 text-[#1F2937]">
                      {formatInline(cell)}
                    </td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    );
  };

  const formatInline = (text: string): React.ReactNode => {
    // Bold: **text**
    const parts = text.split(/(\*\*.*?\*\*|\*.*?\*|`.*?`)/g);

    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="font-semibold text-inherit">{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('*') && part.endsWith('*')) {
        return <em key={i} className="italic text-inherit">{part.slice(1, -1)}</em>;
      }
      if (part.startsWith('`') && part.endsWith('`')) {
        return (
          <code key={i} className="rounded bg-slate-100 px-1 py-0.5 font-mono text-[11px] text-[#6E1D1D]">
            {part.slice(1, -1)}
          </code>
        );
      }
      return part;
    });
  };

  const renderLine = (line: string, key: string) => {
    // Header check
    if (line.startsWith('### ')) {
      return (
        <h4 key={key} className="mt-2 mb-1 text-sm font-semibold text-[#1F2937]">
          {formatInline(line.slice(4))}
        </h4>
      );
    }
    if (line.startsWith('## ')) {
      return (
        <h3 key={key} className="mt-2.5 mb-1 text-sm font-bold text-[#6E1D1D]">
          {formatInline(line.slice(3))}
        </h3>
      );
    }
    if (line.startsWith('# ')) {
      return (
        <h2 key={key} className="mt-3 mb-1 text-base font-bold text-[#6E1D1D]">
          {formatInline(line.slice(2))}
        </h2>
      );
    }

    // Bullet points
    if (line.startsWith('- ') || line.startsWith('* ')) {
      return (
        <div key={key} className="flex items-start gap-2 py-0.5 text-xs text-[#1F2937]">
          <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-[#6E1D1D]" />
          <span className="flex-1">{formatInline(line.slice(2))}</span>
        </div>
      );
    }

    // Numbered list
    const numMatch = line.match(/^(\d+)\.\s+(.*)$/);
    if (numMatch) {
      return (
        <div key={key} className="flex items-start gap-2 py-0.5 text-xs text-[#1F2937]">
          <span className="shrink-0 font-semibold text-[#6E1D1D]">{numMatch[1]}.</span>
          <span className="flex-1">{formatInline(numMatch[2])}</span>
        </div>
      );
    }

    // Default paragraph line
    return (
      <p key={key} className="text-xs leading-relaxed text-[#1F2937]">
        {formatInline(line)}
      </p>
    );
  };

  return <div className="space-y-1">{parseBlocks(content)}</div>;
}
